spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/petrolstation?serverTimezone=GMT
    username: root
    password: 13224903683He,
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true